SHEET_ID = "17FukU_Skp2AvmD4BjHI8IRgj7_chnKF7VrSoGcEPvWI"

[gcp_service_account]
type = "service_account"
project_id = "textile-part-crm"
private_key_id = "0f79c282488adc4b3e6e1b1797eedbf07ab03989"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCuaWMD2bvNmBIb
aTH+Xd6QdjXiTu8Lcnw/crmdRDoltc/qpkySXBK4nTJmWU3Stwdu1bphud6EZ8uW
+fG0ScHo2glaP9k2GMgvN5h4siDiiv23s8TW/fRBmJvKh+29rDp2T81tstAph9Ny
WZj/lPV9kes3Pg1Fgstn01QxScDm4hr+QOUNVsgWGqtZtYJJySexSVgkNJgphvno
NxEphIizC8Ky0D/DFClXvo4ZMOcT01Hejrp1YL9YPJSazUWw15b1ZmDRoDyuKC8V
xV4O9EQdJ9E+9GFc/AiQDrUxP1qFunXx26zUHKFOX2WIORJJugRCC9gV0n9CMw2u
P7J72Cv5AgMBAAECggEAB9yhRXmpm7K4p4/+McCfzomS6Tt0pA1KPilDkQFpJkJZ
TR2nmEtaiVmF/ZNrTM3KTHve4Gvan25MVjxjDE+XfucL1+Eb6fKDsjktKsz2FYV9
ZVakT1VNjtgRtwyZ3LG9muVYVb24i2lfeylAb848+KbnYECa+YtT9D9UQrqCiFsN
YDGltV3hvtZBJ1uJJZ+KxoGGxUFdKyv7yqvyLBGZ4E3OzjuD1UrFaFAMawOBb2bc
GnG8PdRTSkHzJxpyTfqBHOe/WBuzyBbirFAmMXE83Pyn/KCiPKWT+eXC36/W60Wp
cv34LQNgy0qayIIHJ75quRlB9YGLznEORsR+tIr7LwKBgQDnOZFZ+269HVn7fLoX
z+WIbBL1JaCkPUsFXRrarYVNR4cAOEYMr+OHm8+iuk7OShm0afoNFI/NxBhg6ob6
QMxWnrlPu4ylknBo5z33SFRBn5qOh9PfEGuDFah6DtHRTxXZEtiYPJSCWKOmFpfR
ZxvhsAv2UVnNMfvI6WcVzeMA4wKBgQDBGXLvWHsekO/x4ubVnTM2EHSRdi6kg0O+
PTpiElpBgjimklBdUpl/p/Zsle5+RYwTg5YiY4aRIurXsoEvr1lk0I6g4KmpS6Op
TsQw5WFCAVOxjeWFhkBAbcjaMsmhCNZvm7ccXRsJQINQIyYzUHMVbQq5N8hvviJw
AwN+yz8CcwKBgQDWdJ5LRtg+rqp2hghTbY8GKLasiGml6vNZ1jDCAY5RTrX3jjnq
KnhtniXGV+YfjrqoimJRH3EA949k1CC8mrzq2ewl911Lc7aulUrzvzHma5F+AJyR
lzkgK0ZHbtdLun4ZB1G8YPOcsXmW4f2NSoShnhZ6LpmLp4BPp6rknkCc4QKBgBqz
UCc0TuHtHKCPxWdoMzqYj+XFN7HbzLQzdy00aHKCdR7jQGWHFF6IdRSSrsWbDEFu
goYCyQqsj1iAAEj9sBi2leI87njQUrMIhyxTq10bHd2BR2ltJNlD1PAG8cZomG4a
U/mCDkj7OK0ODywtRZyC1WbDBd4dpllisUsJA49tAoGAUP8E03o0eBEW1JYJNsvQ
WkqYfQm7F9QaiJYEaBEHs9qT9Dqp5KhscAAh7FKqflvt7Olr+9wjh9vvg78M5bja
NnhGdhGXJbLbVFCYEY+bo+cmlXKLAvmTU47KMpbfoz85tQt98zlPMZMDyiaUj/va
nOs1Uhex01Wm83YYZwPqTm4=
-----END PRIVATE KEY-----"""
client_email = "crm-bot@textile-part-crm.iam.gserviceaccount.com"
client_id = "115551876548834249661"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/crm-bot%40textile-part-crm.iam.gserviceaccount.com"
universe_domain = "googleapis.com"